---
output: html_document
always_allow_html: yes
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# deepviz

The goal of deepviz is to visualize (simple) neural network architectures.

## Installation

``` r
devtools::install_github("andrie/deepviz")
```

## Load the packages

```{r}
library(deepviz)
library(magrittr)
```


## plot_model()

Create a model

```{r}
require(keras)

model <- keras_model_sequential() %>%
  layer_dense(10, input_shape = 4) %>%
  layer_dense(2, activation = "sigmoid")
```


Plot the model
```{r, fig.height = 2}
model %>% plot_model()
```

Add some more layers and plot

```{r}
model <- keras_model_sequential() %>%
  layer_dense(10, input_shape = 4) %>%
  layer_dense(25, input_shape = 4) %>%
  layer_dense(25, input_shape = 4, activation = "relu") %>%
  layer_dropout(0.25) %>%
  layer_dense(2, activation = "sigmoid")

model %>% plot_model()
```


## plot_deepviz()


### Logistic regression:

```{r, fig.height=1.5}
c(4, 1) %>% 
  plot_deepviz()
```

### One hidden layer:

```{r, fig.height=2.5}
c(4, 10, 1) %>% 
  plot_deepviz()
```

### A multi-layer perceptron (two hidden layers):

```{r, fig.height=3}
c(4, 10, 10, 1) %>% 
  plot_deepviz()
```


### Multi-class classification

```{r, fig.height=3}
c(4, 10, 10, 3) %>% 
  plot_deepviz()
```
