---
title: "Introduction to deepviz"
author: "Andrie de Vries"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Using the `deepviz` package you can plot the architecture of `keras` models.



  
```{r}
library(keras)
library(deepviz)
```

## Simple examples

```{r, eval=FALSE, include=FALSE}
knitr::read_chunk("../inst/examples/example_plot_deepviz.R")
```


```{r cache=FALSE, include=FALSE}
knitr::read_chunk(
  here::here("inst/examples/example_sequential_and_network.R")
)
```

```{r cache=FALSE, include=FALSE}
knitr::read_chunk(
  here::here("inst/examples/example_shared_layer.R")
)
```

### Sequential model

Simple sequential model

```{r sequential, fig.height=8}
```

### Network model

```{r network, fig.height=6}
```

Shared layers

```{r shared, fig.height=6}
```

## Famous architectures

Examples of some famous architectures.



```{r, cache=FALSE, include=FALSE}
knitr::read_chunk(
  here::here("inst/examples/example_network_architectures.R")
)
```

### Depthwise separable convolution

```{r depthwise-separable}
```

### Resnet

```{r resnet}
```


### Classical inception v3

```{r inception_v3}
```




